pipeline {
  environment {
    imagename = "prashanthsukkal/hacicenkins"
    registryCredential = 'prashanthsukkal-dockerhub'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
 //       git([url: 'https://github.com/PrashanthSukkal/hakim.git', branch: 'master', credentialsId: 'prashanthsukkal-github-user-token'])
 	checkout scm

      }
    }
    stage('Building image') {
      steps{
     
      sh "echo AWSKEY && sleep 10"


          }
      }
   
    
    
  }
}
